export const TRANSPARENT_SQUARE48 =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAABlJREFUeNrtwYEAAAAAw6D7U99gBNUSAAAHCTAAAR99LS4AAAAASUVORK5CYII=';
export const TERMINAL = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAQtQTFRFMDAwExMTCQkJBwcHCAgIExMTHh4eDg4OAAAAAAAACAgIBAQEAwMDCAgIb29vh4eHDAwMWFhY8fHx/Pz8bGxsCQkJ1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/Dg4OAQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVBQUFtbW1/v7+u7u7NTU1NjY2r6+vx8fHvLy87OzslJSUBwcHrKysvr6+7+/vlpaWEhISOzs7S0tLLy8vDg4OAgICAQEBCAgIIiIiCgoKAAAACAgIGRkZqLegWAAAAFl0Uk5TLKfMzMyzPcT+/9z///////////////////////////////////////////////////////////////////////////////////////////+++vzTNZuzpEg1JWZdAAAA2ElEQVR4nGNgYGRixg1YWNkY2Dk48QIuBm78Cjg5GQgpgKng4SGggpePXwC/CkEhYRFcSsAqRMXExcUlJPGZISUtLi4jK4fPpfIK4uKKSlgtgvlWWUVcXFgVmynw8FBTFxfX0MTiabgKLW1xcR1dPZwq9A0MgQqMjHHbYmIK9K+ZOW6XWlgC3WlljU0BRIWNrbi4nb0DSKkjFJigquB1Ehd3dgSxXFyhwA3NFndVD0hoeXpBgTe6S32gkeLrBwX+6CrwgCGkwp2gioBAvPJBwQwhoWH4QHgEAOW0PyBW8BCpAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="Layer 2" style="opacity: 0.871" href="#img1" x="0" y="0" /></svg>`;
export const TERMINAL_NOTIFICATION = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEVQTFRFOzIyyhBD1wZF0QZD1QZEwBRAhCg43wZHxQY/xQY/0wZEzQZCywZB0wZE3wZHxwZAxQY/0wZEcC432QZFxQY/1QZEoCA7QhxgrQAAABd0Uk5TLKfMzMyzPcT+/9z///+++vzTNZuzpEgn6j8GAAAAP0lEQVR4nGNgYGRixg1YWNkY2Dk48QIuBm78Cjg5GQgpgKngoYIZoypGVQxuFbwEVfDx45UXEGQQEhbBB0TFAAvNImyX3b/7AAAAAElFTkSuQmCC"/><image width="11" height="16" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAQCAMAAAD3Y3VMAAAAAXNSR0IB2cksfwAAALFQTFRFxR04yh452B48b29vh4eH3h8+WFhY8fHx/Pz8bGxs2h491dXV////p6envy1ATU1N39/f8/Pzn5+f3iJAVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJXDs8xMTE+/v7v7+/xx04kzdA2dnZq6urwS1BiDlAycnJqqqqhDlAVzo70dHRwsLC0idB0h07tbW1/v7+u7u7NTU1r6+vx8fHNjY21h48rKys0iU/HHyVsAAAAHpJREFUeJw9jkcSwkAMBGVMMNAkk03OOQcb/v8wdmtldOqpkVQtIuJ5kk7Gz+ZSzheCooZSGahUXajVoRE2XWi1odPVtV4fgkibwRBGY8eTKczmlhbLlcH1xvJ2Z77uDxaPJ3N5vli83uD+eDqdF7xj9Umiz99NvirzA2J5CEJntWVfAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="Notification" href="#img1" x="0" y="0" /><use id="Layer 2" href="#img2" x="11" y="6" /></svg>`;
export const TERMINAL_FRAMES = [
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="9" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAMAAADKSsaaAAAAAXNSR0IB2cksfwAAAKVQTFRFCAgIb29vh4eHDAwMAAAAWFhY8fHx/Pz8bGxs1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/AQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVtbW1/v7+u7u7NTU1r6+vx8fHNjY2BwcHrKys89xfZwAAAHFJREFUeJwlzkcWwjAMAFFBBIGhBhIwvbcQern/0ZCNVn+hN5JIqRypH6lU41qg1IFG06vVhk43MWmvD2kWmXQwhNglJh2NYTL1ms1hsRRdrTeG7U50f7DO8aSSn22/uFjlCrf7w5ef8HqHax/3/X/wA6ZNB7O27OddAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow0" href="#img2" x="5" y="7" /></svg>`,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="9" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAMAAADKSsaaAAAAAXNSR0IB2cksfwAAAKVQTFRFCAgIb29vh4eHDAwMAAAAWFhY8fHx/Pz8bGxs1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/AQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVtbW1/v7+u7u7NTU1r6+vx8fHNjY2BwcHrKys89xfZwAAAHFJREFUeJwlzkcWwjAMAFFBBIGhBhIwvbcQern/0ZCNVn+hN5JIqRypH6lU41qg1IFG06vVhk43MWmvD2kWmXQwhNglJh2NYTL1ms1hsRRdrTeG7U50f7DO8aSSn22/uFjlCrf7w5ef8HqHax/3/X/wA6ZNB7O27OddAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow1" href="#img2" x="10" y="7" /></svg>`,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="9" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAMAAADKSsaaAAAAAXNSR0IB2cksfwAAAKVQTFRFCAgIb29vh4eHDAwMAAAAWFhY8fHx/Pz8bGxs1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/AQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVtbW1/v7+u7u7NTU1r6+vx8fHNjY2BwcHrKys89xfZwAAAHFJREFUeJwlzkcWwjAMAFFBBIGhBhIwvbcQern/0ZCNVn+hN5JIqRypH6lU41qg1IFG06vVhk43MWmvD2kWmXQwhNglJh2NYTL1ms1hsRRdrTeG7U50f7DO8aSSn22/uFjlCrf7w5ef8HqHax/3/X/wA6ZNB7O27OddAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow1 copy" href="#img2" x="15" y="7" /></svg>`,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="9" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAMAAADKSsaaAAAAAXNSR0IB2cksfwAAAKVQTFRFCAgIb29vh4eHDAwMAAAAWFhY8fHx/Pz8bGxs1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/AQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVtbW1/v7+u7u7NTU1r6+vx8fHNjY2BwcHrKys89xfZwAAAHFJREFUeJwlzkcWwjAMAFFBBIGhBhIwvbcQern/0ZCNVn+hN5JIqRypH6lU41qg1IFG06vVhk43MWmvD2kWmXQwhNglJh2NYTL1ms1hsRRdrTeG7U50f7DO8aSSn22/uFjlCrf7w5ef8HqHax/3/X/wA6ZNB7O27OddAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow1 copy 2" href="#img2" x="20" y="7" /></svg>`,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="9" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAMAAADKSsaaAAAAAXNSR0IB2cksfwAAAKVQTFRFCAgIb29vh4eHDAwMAAAAWFhY8fHx/Pz8bGxs1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/AQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVtbW1/v7+u7u7NTU1r6+vx8fHNjY2BwcHrKys89xfZwAAAHFJREFUeJwlzkcWwjAMAFFBBIGhBhIwvbcQern/0ZCNVn+hN5JIqRypH6lU41qg1IFG06vVhk43MWmvD2kWmXQwhNglJh2NYTL1ms1hsRRdrTeG7U50f7DO8aSSn22/uFjlCrf7w5ef8HqHax/3/X/wA6ZNB7O27OddAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow1 copy 3" href="#img2" x="25" y="7" /></svg>`,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="9" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAMAAADKSsaaAAAAAXNSR0IB2cksfwAAAKVQTFRFCAgIb29vh4eHDAwMAAAAWFhY8fHx/Pz8bGxs1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/AQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVtbW1/v7+u7u7NTU1r6+vx8fHNjY2BwcHrKys89xfZwAAAHFJREFUeJwlzkcWwjAMAFFBBIGhBhIwvbcQern/0ZCNVn+hN5JIqRypH6lU41qg1IFG06vVhk43MWmvD2kWmXQwhNglJh2NYTL1ms1hsRRdrTeG7U50f7DO8aSSn22/uFjlCrf7w5ef8HqHax/3/X/wA6ZNB7O27OddAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow1 copy 4" href="#img2" x="30" y="7" /></svg>`,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="9" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAMAAADKSsaaAAAAAXNSR0IB2cksfwAAAKVQTFRFCAgIb29vh4eHDAwMAAAAWFhY8fHx/Pz8bGxs1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/AQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVtbW1/v7+u7u7NTU1r6+vx8fHNjY2BwcHrKys89xfZwAAAHFJREFUeJwlzkcWwjAMAFFBBIGhBhIwvbcQern/0ZCNVn+hN5JIqRypH6lU41qg1IFG06vVhk43MWmvD2kWmXQwhNglJh2NYTL1ms1hsRRdrTeG7U50f7DO8aSSn22/uFjlCrf7w5ef8HqHax/3/X/wA6ZNB7O27OddAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow1 copy 5" href="#img2" x="35" y="7" /></svg>`,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="4" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAOCAMAAAA/tE0qAAAAAXNSR0IB2cksfwAAAD9QTFRFAAAAGBgYn5+fDw8P/f39cnJyDAwM/////Pz8jo6O8PDwiYmJ+/v7v7+/q6urGRkZqqqqIyMjwsLCFRUVNTU1OwftqQAAADZJREFUeJxjYIADRhDBxAwkWFjZGBjYOTiZGdjZubiBBA8vAzsPHz8Du4AgA4OQMFCJCAMyAAAfSQEMHMB/CQAAAABJRU5ErkJggg=="/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow1 copy 7" href="#img2" x="0" y="7" /></svg>`,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 33 29" width="33" height="29"><defs><image width="33" height="29" id="img1" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACEAAAAdCAMAAAATgvWLAAAAAXNSR0IB2cksfwAAAEhQTFRFLi4uEhISCQkJBgYGCAgIExMTHR0dDQ0NAAAAAAAABwcHBAQEBQUFCAgIBwcHDQ0NAQEBAAAABwcHIiIiCgoKAAAACAgIGRkZqg/WPgAAABh0Uk5TLKfMzMyzPcT+/9z/////vvr80zWbs6RIz/NA7gAAAEZJREFUeJxjYGBkYsYNWFjZGNg5OPECLgZu/Ao4ORkIKRhVMZhV8BBUwUvYFj7K3TFcVOALCogKfgG88oJCDMIioviAmDgAF+kim/iAY30AAAAASUVORK5CYII="/><image width="9" height="14" id="img2" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAOCAMAAADKSsaaAAAAAXNSR0IB2cksfwAAAKVQTFRFCAgIb29vh4eHDAwMAAAAWFhY8fHx/Pz8bGxs1dXV////p6enGBgYTU1N39/f8/Pzn5+fDw8PVFRU7e3t/f39cnJyOTk56urqjo6OXFxc4+Pj8PDwiYmJKioqxMTE+/v7v7+/AQEBICAg2dnZq6urGRkZIiIiycnJqqqqIyMjKysr0dHRwsLCFRUVtbW1/v7+u7u7NTU1r6+vx8fHNjY2BwcHrKys89xfZwAAAHFJREFUeJwlzkcWwjAMAFFBBIGhBhIwvbcQern/0ZCNVn+hN5JIqRypH6lU41qg1IFG06vVhk43MWmvD2kWmXQwhNglJh2NYTL1ms1hsRRdrTeG7U50f7DO8aSSn22/uFjlCrf7w5ef8HqHax/3/X/wA6ZNB7O27OddAAAAAElFTkSuQmCC"/></defs><style>tspan { white-space:pre }</style><use id="BaseTerminal" href="#img1" x="0" y="0" /><use id="_a_Arrow1 copy 8" href="#img2" x="0" y="7" /></svg>`,
];

export function fetchFaviconSrc(node, origin) {
  origin = origin || '';
  let faviconSrc = undefined;
  let nodeList = node.getElementsByTagName('link');
  for (let i = 0; i < nodeList.length; i++) {
    if (
      nodeList[i].getAttribute('rel') == 'icon' ||
      nodeList[i].getAttribute('rel') == 'shortcut icon'
    ) {
      faviconSrc = nodeList[i].getAttribute('href');
    }
  }
  if (!faviconSrc) {
    faviconSrc = origin + '/favicon.ico';
  }

  return new Promise((resolve, reject) => {
    let img = new Image();
    img.onload = function () {
      console.log(`Loaded faviconSrc: ${faviconSrc}`);
      resolve(faviconSrc);
    };

    img.onerror = function () {
      console.log(`Error resolving faviconSrc: ${faviconSrc}`);
      resolve(undefined);
    };
    console.log(`Trying to load faviconSrc: ${faviconSrc}`);
    img.src = faviconSrc;
  });
}
